### ISSUE TITLE
What should `somePath` be?

### ISSUE THREAD

**Issue by mrspeaker** [jsierles/react-native-view-snapshot#1]
Hey, I've got a use-case for this project (so, thank you!) but I'm stuck on what the path should be. Is there some kind of local file system path that should be used (some why to get RCTGetStorageDirectory or something)?

Thanks!

**Comment by mrspeaker** [comment]
Derp - I just noticed the `examples` directory... requires `react-native-fs` for paths. Thanks again!

**Comment by jsierles** [comment]
Cool, glad you got it working. I'll add this to the docs to make it clearer!
