### ISSUE TITLE
saveSnapshotToPath is not a function

### ISSUE THREAD

**Issue by OleksandrBezhan** [jsierles/react-native-view-snapshot#10]
I added .a and .m files to my XCode project and restart app, but still don't see the `saveSnapshotToPath` function.

**Comment by OleksandrBezhan** [comment]
Am I doing something wrong ?

**Comment by jsierles** [comment]
Can you give more details on how you added these files?

**Comment by OleksandrBezhan** [comment]
@jsierles Right click -> "Add files to project" -> selected .m and .h file

**Comment by alnutaifi** [comment]
same here ,,, seems the import statement returns an empty object

**Comment by alnutaifi** [comment]
somehow the ViewSnapshotter.ios.js is missing from the version installed by npm !!

**Comment by jsierles** [comment]
Sorry for the trouble here - I published 0.3.0 which should include these files.
