### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by spenceropope** [jsierles/react-native-view-snapshot#3]
I am getting an error that reads: `undefined is not an object(evaluating 'NativeViewSnapshotter.SaveSnapshotToPath')` from ViewSnapshotter.ios.js. Any idea how to resolve this?

**Comment by jsierles** [comment]
Could you paste your full code in a gist? Thanks!

**Comment by pyrabbit** [comment]
Just in case others needed help with this as well... For those of you that are unfamiliar [like myself] with the development workflow of RN, this particular library requires as stated in the instructions, placing the .m and .h files in the libraries folder of the Xcode project. I originally installed this library globally but I went back into my project and did a `npm install --save react-native-view-snapshot` then navigated from my RN project root to `node_modules/react-native-view-snapshot/` and dragged and dropped the .m and .h files to the libraries folder in Xcode...

**Comment by jsierles** [comment]
Thanks for the comment - I'll be switching this over to use the standard compiled object file, like other plugins use. That should make it easier. I'll also mention it can be installed with https://github.com/rnpm/rnpm.
