### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by gre** [jsierles/react-native-view-snapshot#4]
would be cool :)

**Comment by jsierles** [comment]
I agree! I will need to do this soon for my app. But I really don't know Android too well yet. Any ideas on how to implement this?

**Comment by gre** [comment]
probably can steal/inspire from what I've done in gl-react-native https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/android/src/main/java/com/projectseptember/RNGL/GLCanvas.java#L329 + https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/android/src/main/java/com/projectseptember/RNGL/GLCanvas.java#L180-L242

I have both **"view -> bitmap"** and **"bitmap -> send back to js / save to file"** implemented in iOS and Android. (with also a way to express the quality of the generated snapshot, can also choose between jpg and png. we can probably have this in your lib too)

**Comment by jsierles** [comment]
Ah nice! I'll look at this later this week. Feel free to submit PR :)

**Comment by agenthunt** [comment]
@gre I went through the discussions you have linked. In this case since there is no ViewManager unlike in GLCanvas. And at present there is no way to look up a view given a reactTag id , Right ?

**Comment by gre** [comment]
https://github.com/facebook/react-native/pull/4438#issuecomment-196212926
https://github.com/facebook/react-native/pull/6431

**Comment by jsierles** [comment]
Looks great, nice work @gre

**Comment by jsierles** [comment]
Closing this out in favor of the work being done on React Native core by @gre.

**Comment by gre** [comment]
(not only me, I just made the Android impl)

**Comment by gre** [comment]
@jsierles you might not want to deprecate this package yet https://github.com/facebook/react-native/pull/6431#issuecomment-204418900
if it doesn't make it , i'll PR to you :) but we will still need the method i'm discussing there (resolve a view for a given tag)

**Comment by jsierles** [comment]
Yep, agreed. Definitely want to get back on this.

**Comment by jsierles** [comment]
I'll update the README - meanwhile maybe a new issue needs to be opened on RN just for the view tag ?

**Comment by gre** [comment]
yeah, i'm waiting the guys to respond on that question I asked and i'll probably try to send a PR to RN

**Comment by jsierles** [comment]
Any desire to still work on this? :)

**Comment by TUNER88** [comment]
Any updates?

**Comment by gre** [comment]
sorry, have been busy recently.
there is still my PR out there, that adds the snapshot feature inside React Native.
unfortunately it does not seem to get accepted yet, while the iOS still being there inside RN.
so before RN, finally make a decision for this, we should still provide a PR that will, instead of implementing screenshoting inline in Android, at least provide a method to get a view for a tag.

If anyone want to work on that, please comment, otherwise i'll try to to it as soon as I find time (can't guarantee when)

**Comment by jsierles** [comment]
Thanks for chiming in @gre. I've been looking over this and agree. I would love to work on getting that in. Any tips?

I noticed here that React.findNodeHandle is used:

https://github.com/facebook/react-native/pull/3621/files#diff-0f0686c8f59ec7730c2f90a6bdb590a1R171

**Comment by jsierles** [comment]
To complete this thought, why can't we use the method (https://github.com/facebook/react-native/pull/4438#issuecomment-163533312)[recommended by @kmagiera] to use `UIManager.dispatchViewManagerCommand` for now, which wouldn't require adding a convenience method to React Native I believe?

**Comment by gre** [comment]
As far as I remember:
findNodeHandle is resolving a node in JavaScript side. We want the exact same thing but on the Java side. So a third party can do whatever with a View like screenshoting it.

I think dispatch command only works on a custom view but not on any arbitrary view (to be confirmed)

**Comment by liuxisong** [comment]
hope support android!!

**Comment by gre** [comment]
https://github.com/facebook/react-native/commit/af28de5300b015169b262b440acf1ac30c0044b5

is shipped in RN 0.30.0

so I can do a PR for this.

But best is probably to do this PR after @jsierles refactor the lib so it takes the RN iOS implementation with the same API.

@jsierles what do you think? Also I think it would be great the iOS specific to be in a `ios/` folder like bunch of RN libs do.

Thanks :)

**Comment by jsierles** [comment]
Circumstances have led to me not really needing this plugin anymore. So I won't be doing any refactors in the short term. Feel free to take this on if you need it!

**Comment by gre** [comment]
Hi,

I've just released [react-native-view-shot](https://github.com/gre/react-native-view-shot) which addresses both #4 and #9 .

- It takes the implementation of React Native `UIManager.takeSnapshot`, *(with a minor subset simplification that it doesn't support the "window" screenshot of `takeSnapshot`, I feel it should just be another plugin if there is a need for this)*.
- The Android implementation is just the one I implemented some months ago in [this gist](https://gist.github.com/gre/c466944b8ee7c1b1f17ba79f145d0664).
- There is an example that shows it: https://github.com/gre/react-native-view-shot-example

We are going to maintain it because we need it at [ProjectSeptember](https://github.com/ProjectSeptemberInc), so feel free to use it and help us making it better :)

> @jsierles I hope you don't mind I create a new plugin from scratch as it's written from scratch.

**Comment by jsierles** [comment]
@gre looks good. I will deprecate this one and mention yours in the README. Thanks for picking it up!
