### ISSUE TITLE
Is there a way to save to the Photo library?

### ISSUE THREAD

**Issue by pyrabbit** [jsierles/react-native-view-snapshot#5]
Thanks for all your hard work developing this project. Is there a way to save a screenshot to the photo library?

** Edit 

By the looks of it there is not because iOS locks down access to the CameraRoll. Do you think it is possible to implement this type of behavior? If so I would be interested in trying my hand at some Objective C and create a pull request.

**Comment by jsierles** [comment]
Hey! I think you can use the react native built-in CameraRoll:

https://facebook.github.io/react-native/docs/cameraroll.html

It allows specifying a local file path. So you wouldn't even need to extend this plugin.

**Comment by pyrabbit** [comment]
@jsierles Thanks I will have to look at the documentation again, I was confused how it would have worked. So would I just save this pic to somewhere locally with react-native-view-snapshot and just provide the absolute path of that image to CameraRoll? Or do I have it twisted? Thanks for all your help by the way, I greatly appreciate it :)

**Comment by pyrabbit** [comment]
I found someone of a working solution after playing around with various concepts however when I take a snapshot of the camera preview the resulting picture is completely black.. I will have to work towards a solution on that

```
  takePicture: function() {
    var captureView = this.refs.captureView;
    var capturePath = this.snapshotPath();
    console.log('Taking snapshot');
    ViewSnapshotter.saveSnapshotToPath(React.findNodeHandle(this.refs.captureView), capturePath, (error, successfulWrite) => {
        if (successfulWrite) {
          console.log("Snapshot Saved! " + capturePath);
          CameraRoll.saveImageWithTag(capturePath, function(data) {
            console.log("Saved to CameraRoll");
          }, function(err) {
            console.log(err);
          });
        } else {
          console.log("Snapshot Failed!");
          console.log(error);
        }
    });
  },
```

**Comment by pyrabbit** [comment]
My execution was a little flawed. I should have done what was [not] the obvious at the time. Saving the image to disk then presenting it an image view then taking a snapshot of that. Closing the loop for now. Thanks for the help!

**Comment by jsierles** [comment]
Glad you found a solution. Let me know if you need anything else!
