### ISSUE TITLE
add format and quality options

### ISSUE THREAD

**Issue by gre** [jsierles/react-native-view-snapshot#9]
The React Native iOS snapshot implementation introduced `{ format, quality }` options.
I think it could be interesting to get this in react-native-view-snapshot too.

**Comment by jsierles** [comment]
Yeah agreed - going to need this soon so will look into it.

**Comment by gre** [comment]
Hi,

I've just released [react-native-view-shot](https://github.com/gre/react-native-view-shot) which addresses both #4 and #9 .

- It takes the implementation of React Native `UIManager.takeSnapshot`, *(with a minor subset simplification that it doesn't support the "window" screenshot of `takeSnapshot`, I feel it should just be another plugin if there is a need for this)*.
- The Android implementation is just the one I implemented some months ago in [this gist](https://gist.github.com/gre/c466944b8ee7c1b1f17ba79f145d0664).
- There is an example that shows it: https://github.com/gre/react-native-view-shot-example

We are going to maintain it because we need it at [ProjectSeptember](https://github.com/ProjectSeptemberInc), so feel free to use it and help us making it better :)

> @jsierles I hope you don't mind I create a new plugin from scratch as it's written from scratch.
